<input type="hidden" name="list_all_financial_accounts_data[institution_name][{{ $i }}]" class="input_capitalize form-control required institution_name" placeholder="Name of Institution" value="{{ Helper::validate_key_loop_value('institution_name', $finacial_affairs, $i) }}">
<input type="hidden" name="list_all_financial_accounts_data[street_number][{{ $i }}]" class="input_capitalize form-control  street_number required" placeholder="Address" value="{{ Helper::validate_key_loop_value('street_number', $finacial_affairs, $i) }}">
<input type="hidden" class="input_capitalize form-control city required" name="list_all_financial_accounts_data[city][{{ $i }}]" placeholder="City" value="{{ Helper::validate_key_loop_value('city', $finacial_affairs, $i) }}">
<input type="hidden" class="form-control required state" name="list_all_financial_accounts_data[state][{{ $i }}]" value="{{ Helper::validate_key_loop_value('state', $finacial_affairs, $i) }}">
<input type="hidden" class="form-control zip allow-5digit required" name="list_all_financial_accounts_data[zip][{{ $i }}]" placeholder="Zip code" value="{{ Helper::validate_key_loop_value('zip', $finacial_affairs, $i) }}">
<input type="hidden" class="form-control required account_number allow-4digit" name="list_all_financial_accounts_data[account_number][{{ $i }}]" value="{{ Helper::validate_key_loop_value('account_number', $finacial_affairs, $i) }}">
<input type="hidden" placeholder="MM/DD/YYYY" class="form-control date_filed required date_account_closed" name="list_all_financial_accounts_data[date_account_closed][{{ $i }}]" value="{{ Helper::validate_key_loop_value('date_account_closed', $finacial_affairs, $i) }}">
<input type="hidden" class="form-control required price-field last_balance" name="list_all_financial_accounts_data[last_balance][{{ $i }}]" value="{{ Helper::validate_key_loop_value('last_balance', $finacial_affairs, $i) }}">
<input type="hidden" id="type-of-account_checking_{{ $i }}" class="type_of_account" name="list_all_financial_accounts_data[type_of_account][{{ $i }}]" value="1" required {{ Helper::validate_key_loop_toggle('type_of_account', $finacial_affairs, 1, $i) }}>
<input type="hidden" id="type-of-account_savings_{{ $i }}" class="type_of_account" name="list_all_financial_accounts_data[type_of_account][{{ $i }}]" value="2" required {{ Helper::validate_key_loop_toggle('type_of_account', $finacial_affairs, 2, $i) }}>
<input type="hidden" id="type-of-account-money-market-{{ $i }}" class="type_of_account" name="list_all_financial_accounts_data[type_of_account][{{ $i }}]" value="3" required {{ Helper::validate_key_loop_toggle('type_of_account', $finacial_affairs, 3, $i) }}>
<input type="hidden" id="type-of-account-brokerage-{{ $i }}" class="type_of_account" name="list_all_financial_accounts_data[type_of_account][{{ $i }}]" value="4" required {{ Helper::validate_key_loop_toggle('type_of_account', $finacial_affairs, 4, $i) }}>
<input type="hidden" id="type-of-account-other-{{ $i }}" class="type_of_account" name="list_all_financial_accounts_data[type_of_account][{{ $i }}]" value="5" required {{ Helper::validate_key_loop_toggle('type_of_account', $finacial_affairs, 5, $i) }}>