<?php

namespace App\Mail;

use Illuminate\Mail\Mailable;

class ConciergeAutoGenerated extends Mailable
{
    public $subject;
    protected $message;
    public $data;
    public $hideEmail;

    public function __construct($subject, $message, $data = [], $hideEmail = false)
    {
        $this->subject = $subject;
        $this->message = $message;
        $this->data = $data ?? [];
        $this->hideEmail = $hideEmail;
    }

    public function build()
    {
        $email = $this->view('emails.concierge_auto_generated', [
            'html' => $this->message,
            'data' => $this->data,
            'hideEmail' => $this->hideEmail,
        ])->subject($this->subject);

        return $email;
    }
}
