<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Traits\Common; // Trait
use Illuminate\Support\Facades\Mail;
use App\Helpers\Helper;
use App\Helpers\AddressHelper;
use Illuminate\Support\Facades\Log;

class Docnotuploaded extends Model
{
    use Common;
    public function documentNotifyProcess()
    {
        $days = [3, 17, 25, 39, 54, 69, 73, 89];
        foreach ($days as $key => $value) {
            $clients = $this->checkAfterCreatedDate($value);
            if (!empty($clients)) {
                $this->proceessNotification($clients, $value);
            }
        }
        Log::info("doc not uploaded run");
    }

    private function checkAfterCreatedDate($day)
    {
        $clients = \App\Models\User::whereRaw("DATE_ADD((DATE_FORMAT(users.created_at,'%Y-%m-%d')), INTERVAL ".$day." DAY) = ?", date('Y-m-d'))
                    ->select(['users.id','users.name','users.email','users.device_token','users.device_type','users.document_email_notification','users.document_pushed_notification', 'users.disable_concierge_mail'])
                    ->leftJoin('tbl_client_document_uploaded', 'users.id', '=', 'tbl_client_document_uploaded.client_id')
                    ->leftJoin('tbl_forms_steps_completed', 'users.id', '=', 'tbl_forms_steps_completed.client_id')
                    ->where('users.role', 3)
                    ->where('concierge_service', 1)
                    ->where('disable_concierge_mail', 0)
                    ->groupBy('users.id')
                    ->where(function ($stepsQuery) {
                        $stepsQuery->where('tbl_forms_steps_completed.can_edit', 1)
                        ->orWhere('tbl_forms_steps_completed.can_edit', null)
                        ->orWhere('tbl_client_document_uploaded.client_id', null);
                    })->get();

        return !empty($clients) ? $clients->toArray() : [];
    }
    public function sendTestMsg($id, $day)
    {
        $clients = \App\Models\User::where('id', $id)->select(['users.id','name','email','device_token','device_type','document_email_notification','document_pushed_notification'])->first();
        $clients = !empty($clients) ? $clients->toArray() : [];
        if (!empty($clients)) {
            $clients = [$clients];
            $this->proceessNotification($clients, $day);
        }
    }

    private function proceessNotification($clients, $day)
    {
        foreach ($clients as $client) {
            $user = \App\Models\User::where(['id' => $client['id']])->first();
            $calendyData = \App\Models\CalendlyWebhook::where('client_id', '=', $client['id'])->first();
            $quickCall = false;
            $conciergeAppt = false;
            if (isset($calendyData) && $calendyData['scheduled_event_name'] === 'Process Overview Call') {
                $quickCall = true;
            }
            if (isset($calendyData) && $calendyData['scheduled_event_name'] === 'Client Concierge Service') {
                $conciergeAppt = true;
            }
            $progress = \App\Models\FormsStepsCompleted::getTotalProgressForScheduler($user);
            // for sending text message and email
            if ($progress >= 100) {
                return;
            }
            try {
                $this->sendMessageAndEmailToClient($day, $client, $user, $quickCall, $conciergeAppt, $progress);
            } catch (\Throwable $th) {
                //throw $th;
            }
        }
    }

    public function sendMessageAndEmailToClient($day, $client, $user, $quickCall, $conciergeAppt, $progress)
    {
        $textMessage = $this->getMessageByDay($day, $user, $quickCall, $conciergeAppt, $progress, false);
        $emailMessage = $this->getMessageByDay($day, $user, $quickCall, $conciergeAppt, $progress, true);
        $subject = 'Schedule Your Bankruptcy Assistance Appointment Now';
        $attorney_id = \App\Models\AttorneyEmployerInformationToClient::getClientAttorneyId($user->id);
        if ($day === 25 && $conciergeAppt === false) {
            // text message
            AddressHelper::sendSakariMobileTextMessage($user, $textMessage);
            // email
            if ($client['document_email_notification'] === 1) {
                // concierge client auto generated mail
                if (AttorneySettings::isEmailEnabled($attorney_id, 'client_automated_process_overview_mail', $user->id)) {
                    Mail::to($user->email)->send(new \App\Mail\ConciergeAutoGenerated($subject, $emailMessage));
                }
            }
        }
        if (in_array($day, [3, 17, 39, 54, 69, 73, 89])) {
            // email
            if ($client['document_email_notification'] === 1) {
                // concierge client auto generated mail
                if (AttorneySettings::isEmailEnabled($attorney_id, 'client_automated_process_overview_mail', $user->id)) {
                    Mail::to($user->email)->send(new \App\Mail\ConciergeAutoGenerated($subject, $emailMessage));
                }
            }
        }
    }

    public function getMessageByDay($day, $user, $quickCall, $conciergeAppt, $progress, $forEmail = false)
    {
        $message = '';
        $clientFirstName = Helper::getUserFirstName($user);
        $appointmentUrl = ($forEmail) ? Helper::CALENDY_CONCIERGE_APPOINTMENT_URL."?month=".date('Y-m') : '[url='.Helper::CALENDY_CONCIERGE_APPOINTMENT_URL."?month=".date('Y-m').']';
        $processOverviewCallUrl = ($forEmail) ? Helper::CALENDY_CONCIERGE_PROCESS_OVERVIEW_CALL_URL."?month=".date('Y-m') : '[url='.Helper::CALENDY_CONCIERGE_PROCESS_OVERVIEW_CALL_URL."?month=".date('Y-m').']';
        if ($day === 3) {
            $message = '('.$clientFirstName.'), we know this is a stressful time and process. If you would like to setup a FREE quick 15-minute call with us to go over the process to dramatically lower your stress level, as well as time this will take setup a call here with us: '.$processOverviewCallUrl.'. If you need any help or have any questions, feel free to text us back here.';
            if ($forEmail) {
                $message = '('.$clientFirstName.'), we know this is a stressful time and process. If you would like to setup a FREE quick 15-minute call with us to go over the process to dramatically lower your stress level, as well as time this will take setup a call here with us: <a style="color: #0000EE;" target="_blank" href="'.$processOverviewCallUrl.'" >Quick 15-minute call</a>. If you need any help or have any questions, feel free to text us back here.';
            }
        }
        if ($day === 17) {
            if ($quickCall) {
                $message = "Hello, (".$clientFirstName."), it was a pleasure speaking with you previously. If you need any help with the system, documents, or filling out the questionnaire, please schedule a FREE 45-minute phone appointment using our BK Client Concierge Service Calendly Link. We're here to help! If you need any help or have any questions, feel free to text us back here.";
                if ($forEmail) {
                    $message = "Hello, (".$clientFirstName."), it was a pleasure speaking with you previously. If you need any help with the system, documents, or filling out the questionnaire, please schedule a FREE 45-minute phone appointment using our BK Client Concierge Service Calendly Link. We're here to help! If you need any help or have any questions, feel free to text us back here.";
                }
            }
            if (!$quickCall) {
                $message = "Hello, (".$clientFirstName."), We haven’t heard back from you. We understand that this is a challenging period for you. Our goal is to alleviate your stress and expedite the progress of your case. If you're interested, we invite you to schedule a brief FREE 15-minute call with us here: ".$processOverviewCallUrl." If you need any help or have any questions, feel free to text us back here.";
                if ($forEmail) {
                    $message = "Hello, (".$clientFirstName."), We haven’t heard back from you. We understand that this is a challenging period for you. Our goal is to alleviate your stress and expedite the progress of your case. If you're interested, we invite you to schedule a brief FREE 15-minute call with us here: <a style='color: #0000EE;' target='_blank' href='".$processOverviewCallUrl."' >Quick 15-minute call</a> If you need any help or have any questions, feel free to text us back here.";
                }
            }
        }
        if ($day === 25) {
            if ($quickCall) {
                $message = "(".$clientFirstName."), it was nice meeting you over the phone previously. It’s been about a month since you were invited to the system. If you need any help with the system, documents, and/or filling out the questionnaire please setup a FREE 45-minute appointment here: ".$appointmentUrl." If you need any help or have any questions, feel free to text us back here.";
                if ($forEmail) {
                    $message = "(".$clientFirstName."), it was nice meeting you over the phone previously. It’s been about a month since you were invited to the system. If you need any help with the system, documents, and/or filling out the questionnaire please setup a FREE 45-minute appointment here: <a style='color: #0000EE;' target='_blank' href='".$appointmentUrl."' >Concierge Calendly Link</a> If you need any help or have any questions, feel free to text us back here.";
                }
            }
            if (!$quickCall) {
                $message = "(".$clientFirstName."), We haven’t heard back from you it’s been about a month. We know this is a very tough time for you right now. We would love to be able to help lower your stress level and get your case moving forward with you. If you would like to setup a FREE quick 15-minute call with us to go over this all with you to dramatically lower your stress level and time this takes setup a call here with us: ".$processOverviewCallUrl;
                if ($forEmail) {
                    $message = "(".$clientFirstName."), We haven’t heard back from you it’s been about a month. We know this is a very tough time for you right now. We would love to be able to help lower your stress level and get your case moving forward with you. If you would like to setup a FREE quick 15-minute call with us to go over this all with you to dramatically lower your stress level and time this takes setup a call here with us: <a style='color: #0000EE;' target='_blank' href='".$processOverviewCallUrl."' >New Calendly Link</a>";
                }
            }
        }
        if (in_array($day, [39, 54, 69, 73, 89])) {
            if ($quickCall || $conciergeAppt) {
                $message = "(".$clientFirstName."), we see you have filled out ".$progress."% of your questionnaire. Do you need any help with anything. We would love to help you get this completed and your case filed ASAP. We can help you out FREE on a ".$processOverviewCallUrl." or a FREE 45-minute phone appointment. If you need any help or have any questions, feel free to text us back here. If you already have an appointment, please disregard this text.";
                if ($forEmail) {
                    $message = "(".$clientFirstName."), we see you have filled out ".$progress."% of your questionnaire. Do you need any help with anything. We would love to help you get this completed and your case filed ASAP. We can help you out FREE on a <a style='color: #0000EE;' target='_blank' href='".$processOverviewCallUrl."' >Quick 15-minute call</a> or a FREE 45-minute phone appointment. If you need any help or have any questions, feel free to text us back here. If you already have an appointment, please disregard this text.";
                }
            }
            if (!$quickCall && !$conciergeAppt) {
                $message = "(".$clientFirstName."), we see you have filled out ".$progress."% of your questionnaire and we haven’t heard back from you as of yet. Are you having trouble logging into the questionnaire or are you waiting to start the process for some reason? Please let us know how we can help you. If you need any help or have any questions, feel free to text us back here.";
                if ($forEmail) {
                    $message = "(".$clientFirstName."), we see you have filled out ".$progress."% of your questionnaire and we haven’t heard back from you as of yet. Are you having trouble logging into the questionnaire or are you waiting to start the process for some reason? Please let us know how we can help you. If you need any help or have any questions, feel free to text us back here.";
                }
            }
        }

        return $message;
    }

    public function getDocList($client_id, $attorney_id)
    {
        $client = User::where('id', '=', $client_id)->first();
        $client_id = $client->id;
        $attorney = \App\Models\ClientsAttorney::where("client_id", $client_id)->first();
        $uploadedDocsList = $client->clientDocumentUploaded->toArray();
        $uploadedDocs = array_column($uploadedDocsList, 'document_type');

        // main docs
        // getDocuments($clientType, $includeproperty = 0, $includesub = 0, $includemaster= 0,$includeBankAssistant=0)
        $mainDocs = Helper::getDocuments($client->client_type, false, 1, 1, 0, 0, $attorney->attorney_id);
        $mainDocs = $mainDocs + Helper::getMiscDocs();
        $mainDocs = self::checkAndSetDefaultTypes($mainDocs, $uploadedDocs, 0);
        $mainDocs = self::getDefaultAutoLoans($mainDocs, $uploadedDocs, 0);

        $mainDocuments = [];
        foreach ($mainDocs as $key => $value) {
            $obj = [
                        'document_type' => $key,
                        'document_name' => $value,
                        'document_status' => ''
            ];
            foreach ($uploadedDocsList as $data) {
                if ($data['document_type'] == $key) {
                    $obj = [
                                'document_type' => $key,
                                'document_name' => $value,
                                'document_status' => $data['document_status']
                            ];
                    break;
                }
            }
            array_push($mainDocuments, $obj);
        }

        // additional Docs
        $ClientsAssociateId = ClientsAssociate::getAssociateId($client_id);
        $settingsAttorneyId = !empty($ClientsAssociateId) ? $ClientsAssociateId : $attorney_id;
        $is_associate = !empty($ClientsAssociateId) ? 1 : 0;
        $additionalDocuments = \App\Models\AttorneyDocuments::where(['attorney_id' => $settingsAttorneyId , 'is_associate' => $is_associate])->pluck('document_name', 'document_type')->all();
        $additionalDocs = [];
        foreach ($additionalDocuments as $value) {
            $obj = [
                        'document_type' => $value['document_type'],
                        'document_name' => $value['document_name'],
                        'document_status' => ''
            ];
            foreach ($uploadedDocsList as $data) {
                if ($data['document_type'] == $value['document_name']) {
                    $obj = [
                               'document_type' => $value['document_name'],
                               'document_name' => $value['document_name'],
                               'document_status' => $data['document_status']
                           ];
                    break;
                }
            }
            array_push($additionalDocs, $obj);
        }

        // final Array
        $documents = ['main' => $mainDocuments ?? [], 'additional' => $additionalDocs ?? []];

        return $documents;
    }

}
